### ISSUE TITLE
[QUESTION] Project cleanup

### ISSUE THREAD

**Issue by ghost** [LukasChiama/Banka-App#83]
Hi @LukasChiama,

Do you have any plans on cleaning up the project and preserving the source's folder structure) with Webpack? 

```
-src/
    -app.js (only accesses server-side code)
    -server/
        -models/
        -routes/
        ...
    -client/
        -views/
        -scss/
            -style1.scss
            -style2.scss
            ...
        -js/
            -index.js (es6)
            -other-page.js (es6)
            ...
        ...
-.babelrc
-package.json
-webpack.config.js
...
```

This is related to client and not react client.

**Comment by chialuka** [comment]
HI @nicotravassos, go ahead and raise a Pull Request if you'd like to work on this

**Comment by ghost** [comment]
Thanks @LukasChiama

**Comment by chialuka** [comment]
> Thanks @LukasChiama

Thank you @nicotravassos
